SELECT DISTINCT AGILEGROUP, COUNT(AGILEGROUP) as frequ
FROM DBKDMDB.ADMIN.AGILELABBERS p1
WHERE ((SELECT  count(*) FROM DBKDMDB.ADMIN.AGILELABBERS p2
WHERE p2.AGILEGROUP >= p1.AGILEGROUP ) <=
(SELECT  0.25 * count(*) FROM DBKDMDB.ADMIN.AGILELABBERS) )
GROUP BY p1.AGILEGROUP
DESC
;
